apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-hello-world4
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-hello-world4
  template:
    metadata:
      labels:
        app: java-hello-world4
    spec:
      containers:
      - name: java-hello-world4
        image: harish327/java-hello-world4:13
