apiVersion: v1
kind: Service
metadata:
  name: java-hello-world4-service
spec:
  type: NodePort
  selector:
    app: java-hello-world4
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30008
